# General GitHub Repository Settings
repository:
  license: MIT      # Select a license from the options below
  # License Options:
  # - None
  # - AGPL-3.0 
  # - Apache-2.0 
  # - BSD-2-Clause 
  # - BSD-3-Clause 
  # - EPL-1.0 
  # - GPL-2.0 
  # - GPL-3.0 
  # - LGPL-2.1 
  # - LGPL-3.0 
  # - MIT 
  # - MPL-2.0 
  # - Unlicense 

# MATLAB Toolbox Settings
matlab_toolbox:
  namespace_name: hdtree                         # A unique namespace for your toolbox
  toolbox_name: Hierarchical Data Tree                          # Name of the MATLAB toolbox                  
  author_name: Eivind Hennestad                     
  author_email: ehennestad@gmail.com       
  author_company: 
  toolbox_summary: MATLAB toolbox for representing a hierarchical data tree programmatically or in GUI
  toolbox_description: |
    A MATLAB toolbox containing classes for representing hierarchical data trees, e.g structures, MAT-files, HDF5-files or file-systems, programmatically and in graphical user interfaces
