function testToolbox(varargin)
    installMatBox()
    projectRootDirectory = datatreetools.projectdir();
    matbox.tasks.testToolbox(projectRootDirectory, ...
        "SourceFolderName", "crossref", ...
        "TestsFolderName", fullfile("tools", "tests"), ...
        varargin{:})
end